server:
  port: 8080
spring:
 application:
  name: shop-basics-cloud-eureka


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
    fetch-registry: false
    register-with-eureka: false
  instance:
    hostname: localhost
